### ISSUE TITLE
Images on edit  /infusions/figurelib/admin.php

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_3#11]
When editing a figure the images are not displayed so that you can not see if there are images and therefore can not edit.

**Comment by FrederickChan** [comment]
You can just refer to one of the infusions I've coded. I take latest news infusion as reference.

First, you need something like this for the deletion of image:
https://github.com/php-fusion/PHP-Fusion/blob/9.01/infusions/news/admin/news.php#L505-L518

Then see this how image works.
https://github.com/php-fusion/PHP-Fusion/blob/9.01/infusions/news/admin/news.php#L657-L710

Please figure this. From the current workflow:

- When you create a new - $data['image'] = "" is blank.
- When you edit $data = dbarray($result); and is not blank 

So, we can do - example
````
if (!empty($data['image_album_id'])) {
// show picture and delete submit button
// run query
$result = dbquery("SELECT * FROM ".DB_YOUR_ALBUM." WHERE id='".$data['image_album_id']."'");
if (dbrows($result) > 0) {
echo "<div class='row'>\n";
while ($photo_data = dbarray($result)) {
// html draw your image and button
// for example
echo "<div class='col-xs-12 col-sm-3'>\n";
echo "<img src='...' class='img-responsive'>\n";
echo form_button("delete_photo", "Delete Photo", $data['photo_id']);
echo "</div>\n";
}
echo "</div>\n";
}

} else {
// show file upload.
}
````
So far, in all our infusions, we don't edit photo. Show photo and delete, refresh the form and then show you a file input to allow replacing new photo. 

This part is necessary for UI drawing. You wanted multiple photos. It's greater than my current effort on news. It is going to take time to develop, test and troubleshoot.

==========
*** The future ***
Soon you will see a new php-fusion 9 Dynamics component to handle this more efficiently. What I will do is, when you add a new item, we allow upload to a temporary DB, and a temporary folder (at core level). When defender::safe(), we migrate the photo to a target DB and move the photo to the correct folder.

But the main problem now is, people never learn basic Dynamics yet. If I introduce new API, developer will have a really hard time following, and I will have a very hard time teaching. Plus, I got my own scope of work in PHP-Fusion, so I do not want this for now.

**Comment by FrederickChan** [comment]
Please spend time and finish this part before I look into other issues. :+1:

**Comment by Catzenjaeger** [comment]
> First, you need something like this for the deletion of image:

HERE. `		// delete image
        if (isset($_POST['del_image'])) {
            if (!empty($data['figure_images_image']) && file_exists(IMAGES_FIGURES.$data['figure_images_image'])) {
                unlink(IMAGES_N.$data['figure_images_image']);
            }
            if (!empty($data['figure_images_thumb']) && file_exists(THUMBS_FIGURES.$data['figure_images_thumb'])) {
                unlink(IMAGES_N_T.$data['figure_images_thumb']);
            }
            
            $data['figure_images_image'] = "";
            $data['figure_images_thumb'] = "";

        }`
