### ISSUE TITLE
templates/template_render_figure_items.php - some content will hide

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_3#17]
here i have a area for userfigures. have a user the figure he can add them to your own collection. 
when i make this so will hide all other things under the code of the site. When delete this figure from collection all is seen again. 

Guess its a small error but i cant find them. I have set the code-fragement at last of site. so it will not hide other content

![1](https://cloud.githubusercontent.com/assets/19621858/16619397/2f0502ba-438e-11e6-82f1-622134fd56ac.JPG)
![2](https://cloud.githubusercontent.com/assets/19621858/16619406/3531d08c-438e-11e6-9849-504e7deb2d5d.JPG)

this is the part

`// ####### USERFIGURES  ######################################################
if (iMEMBER) {				
				global $userdata;
				$locale['userfigure_001'] ="Add to collection";
				$locale['userfigure_002'] ="Delete from collection";
				$locale['userfigure_003'] ="The following members have this Figure: ";
				$locale['userfigure_004'] ="No members have this Figure - be the first :)";
				$locale['userfigure_005'] ="FIGURE STATS";
				$locale['userfigure_006'] ="Your Collection";
				
				echo "<div class='well clearfix'>\n";
				echo "<strong>".$locale['userfigure_005']."</strong><br>";
				echo "</div>\n";
				
				//Testausgaben um zu schauen was kommt
				//echo "GET figure_id:<b>".$GET['figure_id']."</b><br>";
				//echo "DATA figure_id:<b>".$data['figure_id']."</b><br>";
				//echo "GET user_id:<b>".$GET['user_id']."</b><br>";
				//echo "DATA user_id (Submitter) :<b>".$data['user_id']."</b><br>";
				//echo "USERDATA user_id:<b>".$userdata['user_id']."</b><hr>";
			
			$resultuf = dbquery(
				"SELECT 			
				fu.user_id, 
				fu.user_name, 
				fu.user_status, 
				fu.user_avatar, 
				fuf.figure_userfigures_figure_id,
				fuf.figure_userfigures_user_id			
				FROM ".DB_FIGURE_USERFIGURES." fuf
				LEFT JOIN ".DB_USERS." fu ON fuf.figure_userfigures_user_id=fu.user_id	
				WHERE figure_userfigures_figure_id='".$data['figure_id']."'
				AND user_id='".$userdata['user_id']."'
				");
				
				$rows = dbrows($resultuf);
	
			if ($rows > 0) { // FIGUR VORHANDEN
						
					while ($datauf = dbarray($resultuf)) {
						
							//echo "<div class='well clearfix'>\n";	
							echo "<tr><td align='center' class='panel-footer' colspan='4' width=''>\n";
							//echo "FIGUR VORHANDEN!<br>";					
							//echo "Anzahl:".$rows;
							//echo "figure_id:".$data['figure_id']."</b><br>";
							//echo "user_id:".$userdata['user_id']."</b><br>";
							//echo "userfigures_figure_id:".$datauf['figure_userfigures_figure_id']."</b><br>";
							//echo "userfigures_user_id:".$datauf['figure_userfigures_user_id']."</b>";
							
							// Form posted
						if (isset($_POST['delete_from_collection'])) {
							// Check Fields
							//$criteriaArray = array(
							//$figure_userfigures_figure_id= form_sanitizer($_POST['figure_userfigures_figure_id'], '', 'figure_userfigures_figure_id'),
							//$figure_userfigures_user_id= form_sanitizer($_POST['figure_userfigures_user_id'], '', 'figure_userfigures_user_id'),
							//);
							//if (defender::safe()) {
									//$inputArray = array(
									//	"figure_userfigures_figure_id" => $data['figure_id'],
									//	"figure_userfigures_user_id" => $userdata['user_id'],);
									//dbquery("
									//DELETE FROM ".DB_FIGURE_USERFIGURES." 
									//WHERE ".$data['figure_id']." ==  ".$datauf['figure_userfigures_figure_id']." 
									//AND ".$userdata['user_id']." ==  ".$datauf['figure_userfigures_user_id']."
									//");
									
									dbquery("
									DELETE FROM ".DB_FIGURE_USERFIGURES." 
									WHERE figure_userfigures_figure_id=".$data['figure_id']." 
									AND figure_userfigures_user_id=".$userdata['user_id']." 
									");
									
									redirect(clean_request("", array("delete_from_collection"), FALSE));
							//}
						}
					}
								echo openform('inputform', 'post', FUSION_REQUEST, array("class" => "",));
								echo form_button("delete_from_collection", $locale['userfigure_002'], $locale['userfigure_002'], array("class" => "btn btn-sm btn-primary"));
								echo "  <a href='http://google.com' class='btn btn-sm btn-primary'>".$locale['userfigure_006']."</a>";
								echo "  <a href='http://google.com' class='btn btn-sm btn-primary'>".$locale['sale']."</a>";
								echo "</td></tr>";
								echo "<p>";
								echo closeform();
								//echo "</div>\n";
								
			} else { // FIGUR NICHT VORHANDEN
									
							//echo "<div class='well clearfix'>\n";	
							echo "<tr><td align='center' class='panel-footer' colspan='4' width=''>\n";	
							//echo "FIGUR NICHT VORHANDEN!<br>";
							//echo "Anzahl:".$rows;
							//echo "userfigures_figure_id:".$datauf['figure_userfigures_figure_id']."</b><br>";
							//echo "userfigures_user_id:".$datauf['figure_userfigures_user_id']."</b>";
								
							// Form posted
						if (isset($_POST['add_to_collection'])) {
											
							// Standard Values for Fields
							$inputArray = array(
							"figure_userfigures_figure_id" => $data['figure_id'], 
							"figure_userfigures_figure_id" => $userdata['user_id'], 
							);
							// Check Fields
							//$inputArray = array(
							//$figure_userfigures_figure_id= form_sanitizer($_POST['figure_userfigures_figure_id'], '', 'figure_userfigures_figure_id'),
							//$figure_userfigures_user_id= form_sanitizer($_POST['figure_userfigures_figure_id'], '', 'figure_userfigures_user_id'),
							//);
							if (defender::safe()) {
									$inputArray = array(
										"figure_userfigures_figure_id" => $data['figure_id'],
										"figure_userfigures_user_id" => $userdata['user_id'],);
									dbquery_insert(DB_FIGURE_USERFIGURES, $inputArray, "save", array());	
									redirect(clean_request("", array("add_to_collection"), FALSE));									
							}
						}
					
								echo openform('inputform', 'post', FUSION_REQUEST, array("class" => "",));
								echo form_button("add_to_collection", $locale['userfigure_001'], $locale['userfigure_001'], array("class" => "btn btn-sm btn-primary"));
								echo "  <a href='http://google.com' class='btn btn-sm btn-primary'>".$locale['userfigure_006']."</a>";
								echo "  <a href='http://google.com' class='btn btn-sm btn-primary'>".$locale['sale']."</a>";
								echo "</td></tr>";
								echo "<p>";
								echo closeform();	
								//echo "</div>\n";															
			}					
	}
// ########### 	folgende User haben die Figure  ##################################				
				
		$resultufc = dbquery(
				"SELECT 			
					fu.user_id, 
					fu.user_name, 
					fu.user_status, 
					fu.user_avatar, 
					fuf.figure_userfigures_figure_id,
					fuf.figure_userfigures_user_id			
				FROM ".DB_FIGURE_USERFIGURES." fuf
				LEFT JOIN ".DB_USERS." fu ON fuf.figure_userfigures_user_id=fu.user_id	
				WHERE figure_userfigures_figure_id='".$data['figure_id']."'
				");		
		
		if (dbrows($resultufc) != 0) {
			
				echo "<hr>";
				echo $locale['userfigure_003'];		
				echo "<p>";	
				
			while ($data = dbarray($resultufc)) {
				
				echo "<tr>\n<td class='side-small' align='left'>".THEME_BULLET."\n";
				echo "<a href='".BASEDIR."profile.php?lookup=".$data['user_id']."' title='".$data['user_name']."' class='side'>\n";
				echo trimlink($data['user_name'], 15)."</a></td>\n</tr>\n";
					
			}
		} else {
				
				echo "<hr>";
				echo $locale['userfigure_004'];	
				echo "<p>";				
		}	
// ########################################`

**Comment by FrederickChan** [comment]
Just scan through, only comment I can give is:

````
        $resultuf = dbquery(
            "SELECT             
            fu.user_id, 
            fu.user_name, 
            fu.user_status, 
            fu.user_avatar, 
            fuf.figure_userfigures_figure_id,
            fuf.figure_userfigures_user_id          
            FROM ".DB_FIGURE_USERFIGURES." fuf
            LEFT JOIN ".DB_USERS." fu ON fuf.figure_userfigures_user_id=fu.user_id  
            WHERE figure_userfigures_figure_id='".$data['figure_id']."'
            AND user_id='".$userdata['user_id']."'
            ");
````

Why use LEFT JOIN? Use INNER JOIN to force 0 if no, and 1 if there is anything, and GROUP BY user_id so result will not collate. 

````
        $resultuf = dbquery(
            "SELECT             
            fu.user_id, 
            fu.user_name, 
            fu.user_status, 
            fu.user_avatar, 
            fuf.figure_userfigures_figure_id,
            fuf.figure_userfigures_user_id          
            FROM ".DB_FIGURE_USERFIGURES." fuf
            INNER JOIN ".DB_USERS." fu ON fuf.figure_userfigures_user_id=fu.user_id  
            WHERE fuf.figure_userfigures_figure_id='".$data['figure_id']."'
            AND fu.user_id='".$userdata['user_id']."' GROUP BY fu.user_id ORDER BY fu.figure_userfigures_figure_id DESC
            ");
````
Will show latest figure first. 

These are not a big matter, you can just try it out slowly. They are the same v7 and v9.

**Comment by Catzenjaeger** [comment]
ok i have change it and i think its solved

**Comment by Catzenjaeger** [comment]
have unfortunately no solution found for the problem

**Comment by Catzenjaeger** [comment]
think is solved .. i have some things rewriten
