### ISSUE TITLE
mycollection.php - missing page nav / print

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_3#18]
in this file i will show all figures of a member. simply it works but i missing a page nav function.

more features are planed: 

- print function (member can print a list of his figures 
- gallery or list view --> member can see his figures as gallery (pic) or as List.
- excel export all data of figures

**Comment by FrederickChan** [comment]
I think you'll be fine here onward. Check the codes, and pagenav is OK.
