### ISSUE TITLE
Slideshow for show the figure images

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_3#19]
todo: change the actual slideshow against a better

i found this: Here is an simple example for image slideshow by using jquery:
--> [http://forums.asp.net/t/1900377.aspx?Dynamically+slide+show+images+on+jquery+slider+from+SQL+database](url)

**Comment by FrederickChan** [comment]
You used plugins, then your best bet is to get support from the plugin author. I won't try to mess on it. Probably styling issue. You can figure this out I'm sure.
