### ISSUE TITLE
Make me an admin and close the issues that has been solved.

### ISSUE THREAD

**Issue by FrederickChan** [Catzenjaeger/FigureLib_3#23]
Hi, I request for 2 things.

1. Please add me as an owner in this repository, so I can push and merge codes, and also you can download changed files.

2. don't leave issues open if it's not an issue any longer.

**Comment by Catzenjaeger** [comment]
ok i have cloesd the issues what finish. 
i have add you as collabrateur is this ok? How can i give you owner rights? 

sorry im in vacation :)

**Comment by FrederickChan** [comment]
Do enjoy your vacation. Yes, I can colloborate in the project now. Do give me some time to prepare for this.

There are a few issues up today on support forum which I need to fix.

**Comment by Catzenjaeger** [comment]
Thanx so much ... normal i can help and test but I have some Days no Internet ... but I try so fast as possible to answer you when you have questions. As Theme i use bootstrap und as admin Theme i use the old admin Theme. I would use other themes but the most dosent work.  You See also on www.aliencollectors.com/site i had try to use a multicolor Theme. But this the theme will not show the help texts . So I must use bootstrap ... this is the uniqe was Show all all correct. Thanx thanx thanx so much ... grettings catzenjaeger

**Comment by Catzenjaeger** [comment]
/site = site without figurelib with a multicolor theme
/test = site for development and test figurelib with bootstrap

**Comment by FrederickChan** [comment]
Then I'll just use the Septenary when i work on it. Tomorrow I'll be going to another state and will return day after. Hardly find time for me to rest..  since PF9 comes first. I'll help as much as I can.
