### ISSUE TITLE
figures.php --> long texts in discreption and Accessories are different

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_3#31]
long texts in description and Accessories are different. i have try it with same texts but in discretions are more empty lines as in Accessories

![ashampoo_snap_2016 08 06_16h56m28s_002_](https://cloud.githubusercontent.com/assets/19621858/17457367/48d7c742-5bf6-11e6-8e07-d68a49cc18cc.jpg)

**Comment by Catzenjaeger** [comment]
error still present

![unbenannt](https://cloud.githubusercontent.com/assets/19621858/17768366/f9239036-6533-11e6-9f9d-d179998d5638.JPG)

**Comment by DavidGuetl** [comment]
Search in "templates/template_render_figure_items.php" by Line 506 for:
`echo "<span class='small' style='word-break: break-all; word-wrap: break-word;'>&nbsp;".nl2br(parseubb(parsesmileys($data['figure_description'])))."</span>\n";`

Replace with:
`echo "<span class='small' style='word-break: break-all; word-wrap: break-word;'>&nbsp;".$data['figure_description']."</span>\n";`

**Comment by Catzenjaeger** [comment]
OK I HAVE SEEN THAT BUT NEVER CHANGE 
what is the difference between this:

&nbsp;".nl2br(parseubb(parsesmileys($data['figure_description'])))."
and this:
&nbsp;".$data['figure_description']."

something with smileys?

**Comment by DavidGuetl** [comment]
nl2br() -> Change Linebreaks \n into <br>
parseubb() -> Parse all BB-Codes in the Text into HTML
parsesmileys() -> Parse all Smilies (BB-Codes) in the Text into IMG-Tag for Smiley Display
----
But as i seen, you use for this Fields in Admin HTML-Code .. so it is not needed.

**Comment by Catzenjaeger** [comment]
ok thanx i change it and close this issue

**Comment by Catzenjaeger** [comment]
its ok :)
