### ISSUE TITLE
mycollection.php --> page nav not correct

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_3#39]
![wew](https://cloud.githubusercontent.com/assets/19621858/17547615/6e3451be-5ee8-11e6-8688-262dbb29175f.jpg)

**Comment by FrederickChan** [comment]
Try FUSION_REQUEST

````
$info['page_nav'] = $max_rows > $fil_settings['figure_per_page'] ? makepagenav($_GET['rowstart'], $fil_settings['figure_per_page'], $max_rows, 3, FUSION_REQUEST) : '';
````

**Comment by Catzenjaeger** [comment]
Page nav works but get me an error in showing when i click forward look images

first pic shows the first site
second pic show the error
![1](https://cloud.githubusercontent.com/assets/19621858/17663213/33036ede-62eb-11e6-9cc7-1dc025541924.JPG)
![2](https://cloud.githubusercontent.com/assets/19621858/17663227/461ae704-62eb-11e6-9ac8-558b12af7416.JPG)

file in github --> ist actually [-->](https://github.com/Catzenjaeger/FigureLib_3/blob/master/infusions/figurelib/mycollection.php)

**Comment by Catzenjaeger** [comment]
same result wit this. error in view again on site 2

`$info['page_nav'] = ($max_rows > $fil_settings['figure_per_page']) ? makepagenav($_GET['rowstart'], $fil_settings['figure_per_page'], $max_rows, 3, FUSION_SELF."?&amp;") : "";`

**Comment by Catzenjaeger** [comment]
ITS A  IMAGE PROBLEM

when i set the image size < 15 pix all is fine 
when i set the image size bigger all is outline and the second image will be show in next column . so all is outline

im looking for a solution that can i show bigger images. i had try different div but no luck

**Comment by Catzenjaeger** [comment]
image problem or whatever

![15](https://cloud.githubusercontent.com/assets/19621858/17769092/5d8d5d6a-6537-11e6-9322-31e686e21fe6.JPG)
![30](https://cloud.githubusercontent.com/assets/19621858/17769096/60ed51d6-6537-11e6-9b61-02e492ada7be.JPG)

File is here: [https://github.com/Catzenjaeger/FigureLib_3/blob/master/infusions/figurelib/mycollection.php](url)

**Comment by DavidGuetl** [comment]
Try this completly recoded File ..
[](http://phpfusion-development.at/mycollection.readContent)

It works without Problems at my Site (Images, Grid, Page-Nav, HTML-Valid, ..)

**Comment by Catzenjaeger** [comment]
YES it looks good thnx

**Comment by Catzenjaeger** [comment]
figurelib/mycollection.php
/test/infusions/figurelib/mycollection.php?rowstart=0
str_repeat() expects exactly 2 parameters, 1 given
Line: 202


Non fatal Runtime Errors 	
figurelib/mycollection.php
/test/infusions/figurelib/mycollection.php
str_repeat() expects exactly 2 parameters, 1 given
Line: 202

**Comment by DavidGuetl** [comment]
Small Tipo ..

Search Line 202 for:
`$rating = ($drating['count_votes'] > 0 ? str_repeat("<img src='".INFUSIONS."figurelib/images/starsmall.png'>".ceil($drating['sum_rating'] / $drating['count_votes'])) : "-");`

Replace with:
`$rating = ($drating['count_votes'] > 0 ? str_repeat("<img src='".INFUSIONS."figurelib/images/starsmall.png'>", ceil($drating['sum_rating'] / $drating['count_votes'])) : "-");`

**Comment by Catzenjaeger** [comment]
LOOKS OK i close it thanx
