### ISSUE TITLE
admin_figurelib.php --> SQLSTATE[42000]: Syntax error or access violation: 1064

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_3#43]
Driver/PDOMySQL.php
/test/infusions/figurelib/admin.php?aid=039378461d19a8f3&section=figurelib_form
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 5
Line: 108

**Comment by Catzenjaeger** [comment]
error not found ... i look in admin.php and admin_figurelib.php ... nothing

need help :)

**Comment by Catzenjaeger** [comment]
error comes when click on here:

![unbenannt](https://cloud.githubusercontent.com/assets/19621858/17775316/fceb4212-6557-11e6-9f8e-8df15c2935e0.JPG)

**Comment by DavidGuetl** [comment]
Open admin_figurelib.php and search in Line 121 for:
`".(multilang_table("FI") ? "WHERE figure_language='".LANGUAGE."' AND" : "WHERE")." ");`

Replace it with:
`".(multilang_table("FI") ? "WHERE figure_language='".LANGUAGE."'" : "")." ");`

**Comment by Catzenjaeger** [comment]
gott sei dank .. ich bin gerade 10000m tode gestorben :)
sieht gut aus

**Comment by DavidGuetl** [comment]
Du solltest diese Issue hier ebenfalls schließen ;)

**Comment by Catzenjaeger** [comment]
:+1: thnx
