### ISSUE TITLE
/templates/template_render_figure.php --> right panels not correct shown

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_3#46]
small error in gallery view when no figures available

File is here: [https://github.com/Catzenjaeger/FigureLib_3/blob/master/infusions/figurelib/templates/template_render_figure.php](url)

![unbenannt](https://cloud.githubusercontent.com/assets/19621858/17768217/55190d2c-6533-11e6-85b4-b0ef3f217925.JPG)

**Comment by DavidGuetl** [comment]
Search in Line 71 and remove:
`openside('');`

Add this Code into Line 60
`openside('');`

**Comment by Catzenjaeger** [comment]
OMG where was my eyes :) solved thanx
