### ISSUE TITLE
template_render_figure.php --> image not found - ????? 

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_3#48]
template_render_figure.php 

`if(dbrows($result2)){						 
										while($data2 = dbarray($result2)){						
											echo "<center><a href='".$data['figure']['link']."'><img src='".($data2['figure_images_thumb'] ? THUMBS_FIGURES.$data2['figure_images_thumb'] : IMAGES."imagenotfound.jpg")."' alt='".trimlink($data['figure_title'],100)."' title='".trimlink($data['figure_title'],50)."' style='border:0px;max-height:100px;max-width:100px' /><br />";						
										}										
									} else { 									
											echo "<center><a href='".$data['figure']['link']."'><img src='".IMAGES."imagenotfound.jpg' alt='".trimlink($data['figure_title'],100)."' title='".trimlink($data['figure_title'],50)."' style='border:0px;max-height:100px;max-width:100px' /><br />";
											}`

change the image to 
INFUSIONS.$inf_folder."/images/default.png

but the system says error image_folder
folder is declared in infusion.db .... code with this image works in mycollection fine but here not :(

![unbenannt](https://cloud.githubusercontent.com/assets/19621858/17773204/7f550d9c-654d-11e6-8ec1-42566fb04194.JPG)

**Comment by DavidGuetl** [comment]
Try: INFUSIONS."figurelib/images/default.png

**Comment by Catzenjaeger** [comment]
LOL that was it thanx
