### ISSUE TITLE
figures.php --> Undefined variable: indicators

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_3#49]
templates/template_render_figure_items.php
/test/infusions/figurelib/figures.php?figure_id=4
Undefined variable: indicators
Line: 154

have change something here and get now an notice :(

**Comment by DavidGuetl** [comment]
It doesnt work Line 154-156:
```
echo "<ol class='carousel-indicators'>\n";
echo $indicators;
echo "</ol>\n";
```

Because there are no Images in the DB, so there want be any Indicators. If you want to display just the Slider with "no Photo - Register" text, you can remove the lines above (line154-156)

**Comment by Catzenjaeger** [comment]
I want to show the "default" image and text. As can be seen here.
![unbenannt](https://cloud.githubusercontent.com/assets/19621858/17773473/e6a49ade-654e-11e6-8b73-b107e887f9ed.JPG)

**Comment by DavidGuetl** [comment]
Ok, so you can remove Line 154-156.

**Comment by Catzenjaeger** [comment]
Thanx guess its solved
