### ISSUE TITLE
Images submit dosent work

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_3#5]
dosent work

**Comment by FrederickChan** [comment]
You are using multiple input picture. That means you need to sanitize multiple times. I'll code the relevant part changes for you.

**Comment by FrederickChan** [comment]
I can see why you have issue. Your form will not upload image unless you turn on 'enctype' to true..

**Comment by FrederickChan** [comment]
You also have a spelling mistake at figure_usedprice during post.

I turned off redirect, but you can turn it back on after posting successfully.

<b>Tip</b>: You can use print_p($_POST); print_p($_FILES); to see data that go through next refresh without redirect.

**Comment by Catzenjaeger** [comment]
the currently submit.php can not work. How can the be used to connect with the images? The data is stored in DB_SUBMISSION and the images into the DB_FIGURE_IMAGES. But how can I find the right picture to Figure again later?
