### ISSUE TITLE
breadcrumbs to long (to long text)

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_3#50]
![unbenannt](https://cloud.githubusercontent.com/assets/19621858/17774722/3b586622-6555-11e6-9078-78874cd8c645.JPG)

somewhere i have to add a trimlink :)

**Comment by Catzenjaeger** [comment]
its in figures.php guess but where .. 
some try were unsuccessful

**Comment by DavidGuetl** [comment]
**Please update figures.php here!**

Breadcrumb -> Detail View ..
Open figures.php and search for:
`add_breadcrumb(["link" => INFUSIONS."figurelib/figures.php?figure_id=".$_GET['figure_id'], "title" => $figureTitle]);`

Replace with
`add_breadcrumb(["link" => INFUSIONS."figurelib/figures.php?figure_id=".$_GET['figure_id'], "title" => trimlink($figureTitle, 45)]);`

Set 45 to Charnumber what you want.

**Comment by Catzenjaeger** [comment]
war nah dran ... die Klammer hinten hat gefehlt in meiner version 
deshalb gings nicht :)
danke


Am 18.08.2016 um 16:24 schrieb David:
