### ISSUE TITLE
Question: how can I text in the lists align horizontally.

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_3#52]
how can I text in the lists align horizontally. At the moment, the text is higher than the center of the image
![ashampoo_snap_2016 08 18_18h05m16s_002_](https://cloud.githubusercontent.com/assets/19621858/17781200/abbb0eec-656e-11e6-8bb5-cfd31b193da1.jpg)

**Comment by DavidGuetl** [comment]
Insert by the Linenumbers at the End of this comment after
`class='side-small'`
the following
`style='line-height: 40px;'`

Attention: 40px must always the same height of Images.
Lines: 230, 237, 244, 251, 259, 263 and 271

**Comment by Catzenjaeger** [comment]
perfekt :) 
works thx
