### ISSUE TITLE
TODO & FIX search

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_3#53]
Files here: [https://github.com/Catzenjaeger/FigureLib_3/tree/master/includes/search](url)

atm it dosen t work

**Comment by Catzenjaeger** [comment]
Submitter: Catzenjaeger | Manufacturer: Alien Enterprise | Publish date: 1970

date is wrong - can we add more infos example one image when aviable

**Comment by DavidGuetl** [comment]
Date is correct (Publish Date), selected at Figure "Test1" year 1973, in search it wil display 1973.

**Comment by Catzenjaeger** [comment]
hmnnn 
1.) ok thanx i test it again
2.) try "alien" = no result but we have it in manufacturer. looking this script only in title or hole figurelib?

**Comment by DavidGuetl** [comment]
Only Figure.

**Comment by Catzenjaeger** [comment]
kann man das verfeinerin irgendwie? Ich meine ich werde da zirka 1000 
Figuren eventuell haben ... die meisten heissen ALien ....weisst was ich 
meine?


Am 19.08.2016 um 10:52 schrieb David:

**Comment by DavidGuetl** [comment]
In den Suchfeldern schwer.

Da wäre es besser eine neue Suchseite aufzusetzen.

**Comment by Catzenjaeger** [comment]
schade ... nun ja ... das muss dann irgendwann einmal .. erstmals muss 
alles laufen

man könnte so ne seite machen wo man zB alle manufacturer listet --> der 
user klickt dann drauf und sieht alle Figuren von diesen hersteller

genauso mit den anderen Kritierien

Ich hatte ja schon einaml angeregt ob man vielleicht nicht die seite wo 
die ganzen kategorien zu sehen sind noch eine Unterseite macht wo alle 
Hersteller einer kategorie erscheinen und erst dann wenn der user 
draufklickt die eigentlichen figuren zu sehen sind

Am 19.08.2016 um 11:03 schrieb David:

**Comment by DavidGuetl** [comment]
Könnte man machen, aber würde sagen das sind änderungen, welche man nachdem alles funktioniert noch immer einbauen kann.

**Comment by Catzenjaeger** [comment]
ok :)

**Comment by Catzenjaeger** [comment]
move to later - closed for the moment
