### ISSUE TITLE
admin_figurelib.php - EDIT FIGURE - no longer works!!!

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_3#55]
![ashampoo_snap_2016 08 18_18h33m39s_004_](https://cloud.githubusercontent.com/assets/19621858/17782121/5ab5bbc4-6572-11e6-94f6-c1db5b75f46d.jpg)
![ashampoo_snap_2016 08 18_18h34m50s_005_](https://cloud.githubusercontent.com/assets/19621858/17782155/81bd1f32-6572-11e6-989f-04542579f9cc.jpg)

someone is wrong. i see only the images now all data from all other fields are blank

file: admin_figurelib.php

**Comment by Catzenjaeger** [comment]
ich habe mal ältere Dateien noch einmal probiert --- überall fehlen Daten also gehe ich davon aus, dass es nicht diese Datei ist sondern woanders. eventuell die admin.php

**Comment by DavidGuetl** [comment]
Möglicherweise ein Fehler deinerseits?
Habe gerade das aktuelle Paket von hier geladen - keine Probleme.

**Comment by Catzenjaeger** [comment]
ich auch kommt nichts keine daten

**Comment by DavidGuetl** [comment]
Nur bei der einen Figur oder bei allen?
Fehlermeldungen?
Inhalt in DB?

**Comment by Catzenjaeger** [comment]
keine Meldungen bei allen edit vorgängen ... egal ob ich einen von den current figures editiere oder die eine die in den submissions hängt. Die werden beide in der gleichen "form" geöffnet. n

**Comment by Catzenjaeger** [comment]
jetzt laufen ganz viele meldungen ein

/test/infusions/figurelib/figures.php?figure_cat_id=3
include(): Failed opening '../../infusions/figurelib/templates/template_render_figure_items.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear')
Line: 53
7 seconds ago 	
Non fatal Runtime Errors 	
figurelib/figures.php
/test/infusions/figurelib/figures.php?figure_cat_id=3
include(../../infusions/figurelib/templates/template_render_figure_items.php): failed to open stream: No such file or directory

**Comment by DavidGuetl** [comment]
Das ganze lag an Issue #43 

Einfach die admin_figure.php mit der folgenden ersetzten:
[VIEW FILE](http://phpfusion-development.at/admin_figurelib.readContent)

Meines erachtens können nun Issue #43 und #55 geschlossen werden (insofern es bei dir auch Fehlerfrei läuft).

**Comment by Catzenjaeger** [comment]
:+1:  :)
