### ISSUE TITLE
admin_figurelib.php --> Filter doesn't work

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_3#56]
Filter doesn't work 
always no figures and no return button

![1](https://cloud.githubusercontent.com/assets/19621858/17784453/db3ff2fa-657c-11e6-8f5a-ca0c30d4b0b6.jpg)
![ashampoo_snap_2016 08 18_19h47m44s_008_](https://cloud.githubusercontent.com/assets/19621858/17784462/e3bf6f82-657c-11e6-849e-3ea214a89169.jpg)

is this this?

[Driver/PDOMySQL.php
/test/infusions/figurelib/admin.php?aid=2b2a846b19e1494c&section=figurelib&filter_cid=2
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE figure_freigabe = 1 ORDER by figure_title asc, figure_datestamp desc LI' at line 13
Line: 108](url)

**Comment by DavidGuetl** [comment]
For SQL Statement, search in "admin.php" in Line 210/211 for:
".$catFilter."
WHERE figure_freigabe = 1

Replace it with:
".($catFilter ? $catFilter." AND " : "WHERE ")." figure_freigabe='1'

For HTML-View search in Line 218 for
if ($rows > 0) {
and remove it.

After add the removed Code after this (line 252)
```
	if ($total_rows > $rows) {
		echo makepagenav($rowstart, $limit, $total_rows, $limit, clean_request("", array(
									  "aid",
									  "section"
								  ), TRUE)."&amp;");
	}
	echo "</div>\n";
```

**Comment by Catzenjaeger** [comment]
hmnn sure? 

1.) ".$catFilter."
WHERE figure_freigabe = 1

Replace it with:
".($catFilter ? $catFilter." AND " : "WHERE ")." figure_freigabe='1' --> done and ok

2.) if ($rows > 0) { --> und die schliessende Klammer? 

und wo das andere einfügen? ich mach dich mal zum admin hier da kannst direkt rumcoden :) LOL

**Comment by DavidGuetl** [comment]
Ok, füge mich hinzu dann mache ich dass direkt ;)

**Comment by Catzenjaeger** [comment]
bist admin :)

**Comment by DavidGuetl** [comment]
Also ich hab die Datei mal bearbeitet .. 

Siehst du nun die Änderungen und kannst diese Verwenden?

**Comment by Catzenjaeger** [comment]
geilllll :) :+1: :+1::+1:

**Comment by DavidGuetl** [comment]
Und wie bekommst du nun die Änderung in deine Dateien hier? Hab ja früher nie Github benützt :P

**Comment by Catzenjaeger** [comment]
hier klicken. Dann sieht man deine Änderungen. grün neu rot= gelöscht
![ashampoo_snap_2016 08 18_20h56m08s_009_](https://cloud.githubusercontent.com/assets/19621858/17786685/45b5daa6-6586-11e6-86b6-14c8d1c71975.jpg)

**Comment by DavidGuetl** [comment]
Ah wir reden einander vorbei, ich meinte jetzt den Branch was man ja auch herunterladen kann. Denn lade ich jz das komplette Paket ist wieder die alte Datei drinnen :dancer:

**Comment by Catzenjaeger** [comment]
hmn ich glaube du must das als pull request machen ... dann kann man das freigeben
ansonsten adde ich die datei manuell

**Comment by DavidGuetl** [comment]
Hat anscheinend doch funktioniert ^^ sehr intressant dieses Zeugs :P

**Comment by Catzenjaeger** [comment]
ich habe den pull mal gemacht und die daten sind jetzt drinn

**Comment by DavidGuetl** [comment]
Ok, dann kannst du diese Issue ja schließen ;)
