### ISSUE TITLE
submit.php --> submit again and again

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_3#57]
atm it is possible to get back in browser and send the figure including the images again and again.

is it possible to stop this?

**Comment by DavidGuetl** [comment]
i would say: NO.

You can add a check, that its not allowed to add Figures with the same Name .. but i dont know if there more Figures with same Name?

**Comment by Catzenjaeger** [comment]
this is the point! But can we stop a resubmit with  a session or so? forms can be destroyed with sessions

**Comment by DavidGuetl** [comment]
At the Moment, i dont know anything about it .. best solution, check if the same Figure Name with same Options exists in DB, if yes, set a Notice.

**Comment by Catzenjaeger** [comment]
Notive? I think in this case we haveto do the submitter send a message 
or automatic rejection with hint "figure available"


Am 18.08.2016 um 20:50 schrieb David:

**Comment by Catzenjaeger** [comment]
ok goes on todo list for later atm closed
